# Generated by Django 6.0.5 on 2026-06-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsession',
            name='title',
            field=models.CharField(default='Workout', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='workout_type',
            field=models.CharField(choices=[('push', 'Push'), ('pull', 'Pull'), ('legs', 'Legs'), ('upper', 'Upper'), ('lower', 'Lower'), ('full_body', 'Full Body'), ('custom', 'Custom')], default='custom', max_length=20),
        ),
    ]
