# Generated by Django 6.0.5 on 2026-06-14 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_legacy_exercise_data(apps, schema_editor):
    Exercise = apps.get_model('workouts', 'Exercise')
    Exercise.objects.filter(muscle_group='legs').update(muscle_group='quads')
    Exercise.objects.filter(muscle_group='core').update(muscle_group='abs')
    Exercise.objects.filter(created_by__isnull=False).update(is_custom=True)


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_bodyweightentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='exercise',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='exercise',
            name='equipment',
            field=models.CharField(choices=[('barbell', 'Barbell'), ('dumbbell', 'Dumbbell'), ('machine', 'Machine'), ('cable', 'Cable'), ('bodyweight', 'Bodyweight'), ('kettlebell', 'Kettlebell'), ('resistance_band', 'Resistance Band'), ('smith_machine', 'Smith Machine'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='exercise',
            name='exercise_type',
            field=models.CharField(choices=[('compound', 'Compound'), ('isolation', 'Isolation')], default='compound', max_length=20),
        ),
        migrations.AddField(
            model_name='exercise',
            name='is_custom',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_exercises', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(migrate_legacy_exercise_data, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='exercise',
            name='muscle_group',
            field=models.CharField(choices=[('chest', 'Chest'), ('back', 'Back'), ('shoulders', 'Shoulders'), ('biceps', 'Biceps'), ('triceps', 'Triceps'), ('forearms', 'Forearms'), ('abs', 'Abs'), ('quads', 'Quads'), ('hamstrings', 'Hamstrings'), ('glutes', 'Glutes'), ('calves', 'Calves'), ('full_body', 'Full Body')], max_length=20),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=140),
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_custom', True), ('created_by__isnull', False)), models.Q(('is_custom', False), ('created_by__isnull', True)), _connector='OR'), name='exercise_custom_state_matches_owner'),
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.UniqueConstraint(condition=models.Q(('is_custom', True)), fields=('name', 'created_by'), name='unique_custom_exercise_per_user'),
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.UniqueConstraint(condition=models.Q(('is_custom', False)), fields=('name',), name='unique_builtin_exercise_name'),
        ),
        migrations.AddField(
            model_name='favoriteexercise',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='workouts.exercise'),
        ),
        migrations.AddField(
            model_name='favoriteexercise',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_exercises', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='favoriteexercise',
            constraint=models.UniqueConstraint(fields=('user', 'exercise'), name='unique_favorite_exercise_per_user'),
        ),
    ]
