# Generated by Django 6.0.5 on 2026-08-30 08:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0006_accountprofile_accountactioncode_oauthidentity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bodyweightentry',
            constraint=models.CheckConstraint(condition=models.Q(('weight__gte', 20)), name='bodyweight_gte_20'),
        ),
        migrations.AddConstraint(
            model_name='bodyweightentry',
            constraint=models.CheckConstraint(condition=models.Q(('weight__lte', 500)), name='bodyweight_lte_500'),
        ),
        migrations.AddConstraint(
            model_name='exerciseset',
            constraint=models.CheckConstraint(condition=models.Q(('set_number__gte', 1)), name='exercise_set_number_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='exerciseset',
            constraint=models.CheckConstraint(condition=models.Q(('set_number__lte', 1000)), name='exercise_set_number_lte_1000'),
        ),
        migrations.AddConstraint(
            model_name='exerciseset',
            constraint=models.CheckConstraint(condition=models.Q(('weight__gte', 0)), name='exercise_set_weight_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='exerciseset',
            constraint=models.CheckConstraint(condition=models.Q(('weight__lte', 2000)), name='exercise_set_weight_lte_2000'),
        ),
        migrations.AddConstraint(
            model_name='exerciseset',
            constraint=models.CheckConstraint(condition=models.Q(('reps__gte', 1)), name='exercise_set_reps_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='exerciseset',
            constraint=models.CheckConstraint(condition=models.Q(('reps__lte', 1000)), name='exercise_set_reps_lte_1000'),
        ),
    ]
