# Generated by Django 6.0.5 on 2026-08-30 12:31

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def complete_existing_workouts(apps, schema_editor):
    workout_session = apps.get_model("workouts", "WorkoutSession")
    workout_session.objects.update(
        status="completed",
        completed_at=models.F("created_at"),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0007_bodyweightentry_bodyweight_gte_20_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workoutsession',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.AddField(
            model_name='exerciseset',
            name='notes',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='exerciseset',
            name='rir',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exerciseset',
            name='rpe',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed')], default='draft', max_length=12),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RunPython(
            complete_existing_workouts,
            migrations.RunPython.noop,
        ),
        migrations.AddIndex(
            model_name='workoutsession',
            index=models.Index(fields=['user', 'status', '-date'], name='workouts_wo_user_id_96a3b8_idx'),
        ),
        migrations.AddConstraint(
            model_name='exerciseset',
            constraint=models.CheckConstraint(condition=models.Q(('rpe__isnull', True), ('rpe__gte', 1), _connector='OR'), name='exercise_set_rpe_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='exerciseset',
            constraint=models.CheckConstraint(condition=models.Q(('rpe__isnull', True), ('rpe__lte', 10), _connector='OR'), name='exercise_set_rpe_lte_10'),
        ),
        migrations.AddConstraint(
            model_name='exerciseset',
            constraint=models.CheckConstraint(condition=models.Q(('rir__isnull', True), ('rir__lte', 10), _connector='OR'), name='exercise_set_rir_lte_10'),
        ),
        migrations.AddConstraint(
            model_name='exerciseset',
            constraint=models.UniqueConstraint(fields=('workout_session', 'exercise', 'set_number'), name='unique_set_number_per_workout_exercise'),
        ),
        migrations.AddConstraint(
            model_name='workoutsession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'draft')), fields=('user',), name='unique_active_workout_draft_per_user'),
        ),
    ]
