# Generated by Django 6.0.5 on 2026-08-30 12:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0008_alter_workoutsession_options_exerciseset_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='workoutsession',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', True), ('status', 'draft')), models.Q(('completed_at__isnull', False), ('status', 'completed')), _connector='OR'), name='workout_status_matches_completion_time'),
        ),
    ]
